#pragma once

#include <lib/core/DataModelTypes.h>

using chip::EndpointId;

void ESPMatterAccessControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAccessControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterAccountLoginClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAccountLoginClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterActionsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterActionsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterActivatedCarbonFilterMonitoringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterActivatedCarbonFilterMonitoringClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterAdministratorCommissioningClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAdministratorCommissioningClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterAirQualityClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAirQualityClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterApplicationBasicClusterServerInitCallback(EndpointId endpoint);
void ESPMatterApplicationBasicClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterApplicationLauncherClusterServerInitCallback(EndpointId endpoint);
void ESPMatterApplicationLauncherClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterAudioOutputClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAudioOutputClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterBallastConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBallastConfigurationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterBasicInformationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBasicInformationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterBindingClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBindingClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterBooleanStateClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBooleanStateClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterBooleanStateConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBooleanStateConfigurationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterBridgedDeviceBasicInformationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBridgedDeviceBasicInformationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterCameraAvSettingsUserLevelManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCameraAvSettingsUserLevelManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterCameraAvStreamManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCameraAvStreamManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterCarbonDioxideConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCarbonDioxideConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterCarbonMonoxideConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCarbonMonoxideConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterChannelClusterServerInitCallback(EndpointId endpoint);
void ESPMatterChannelClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterChimeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterChimeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterClosureControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterClosureControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterClosureDimensionClusterServerInitCallback(EndpointId endpoint);
void ESPMatterClosureDimensionClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterColorControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterColorControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterCommissionerControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCommissionerControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterCommodityMeteringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCommodityMeteringClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterCommodityPriceClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCommodityPriceClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterCommodityTariffClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCommodityTariffClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterContentAppObserverClusterServerInitCallback(EndpointId endpoint);
void ESPMatterContentAppObserverClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterContentControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterContentControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterContentLauncherClusterServerInitCallback(EndpointId endpoint);
void ESPMatterContentLauncherClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterDescriptorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDescriptorClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterDeviceEnergyManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDeviceEnergyManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterDeviceEnergyManagementModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDeviceEnergyManagementModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterDiagnosticLogsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDiagnosticLogsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterDishwasherAlarmClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDishwasherAlarmClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterDishwasherModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDishwasherModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterDoorLockClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDoorLockClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterEcosystemInformationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEcosystemInformationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterElectricalEnergyMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterElectricalEnergyMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterElectricalGridConditionsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterElectricalGridConditionsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterElectricalPowerMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterElectricalPowerMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterEnergyEvseClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEnergyEvseClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterEnergyEvseModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEnergyEvseModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterEnergyPreferenceClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEnergyPreferenceClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterEthernetNetworkDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEthernetNetworkDiagnosticsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterFanControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFanControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterFaultInjectionClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFaultInjectionClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterFixedLabelClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFixedLabelClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterFlowMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFlowMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterFormaldehydeConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFormaldehydeConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterGeneralCommissioningClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGeneralCommissioningClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterGeneralDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGeneralDiagnosticsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterGroupKeyManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGroupKeyManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterGroupsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGroupsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterHepaFilterMonitoringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterHepaFilterMonitoringClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterIcdManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterIcdManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterIdentifyClusterServerInitCallback(EndpointId endpoint);
void ESPMatterIdentifyClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterIlluminanceMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterIlluminanceMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterJointFabricAdministratorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterJointFabricAdministratorClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterJointFabricDatastoreClusterServerInitCallback(EndpointId endpoint);
void ESPMatterJointFabricDatastoreClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterKeypadInputClusterServerInitCallback(EndpointId endpoint);
void ESPMatterKeypadInputClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterLaundryDryerControlsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLaundryDryerControlsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterLaundryWasherControlsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLaundryWasherControlsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterLaundryWasherModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLaundryWasherModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterLevelControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLevelControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterLocalizationConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLocalizationConfigurationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterLowPowerClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLowPowerClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterMediaInputClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMediaInputClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterMediaPlaybackClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMediaPlaybackClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterMessagesClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMessagesClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterMeterIdentificationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMeterIdentificationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterMicrowaveOvenControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMicrowaveOvenControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterMicrowaveOvenModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMicrowaveOvenModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterModeSelectClusterServerInitCallback(EndpointId endpoint);
void ESPMatterModeSelectClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterNetworkCommissioningClusterServerInitCallback(EndpointId endpoint);
void ESPMatterNetworkCommissioningClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterNitrogenDioxideConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterNitrogenDioxideConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOccupancySensingClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOccupancySensingClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOnOffClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOnOffClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOperationalCredentialsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOperationalCredentialsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOperationalStateClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOperationalStateClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOtaSoftwareUpdateProviderClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOtaSoftwareUpdateProviderClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOtaSoftwareUpdateRequestorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOtaSoftwareUpdateRequestorClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOvenCavityOperationalStateClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOvenCavityOperationalStateClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOvenModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOvenModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterOzoneConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOzoneConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPm10ConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPm10ConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPm1ConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPm1ConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPm25ConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPm25ConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPowerSourceClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPowerSourceClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPowerSourceConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPowerSourceConfigurationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPowerTopologyClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPowerTopologyClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPressureMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPressureMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterProxyConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterProxyConfigurationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterProxyDiscoveryClusterServerInitCallback(EndpointId endpoint);
void ESPMatterProxyDiscoveryClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterProxyValidClusterServerInitCallback(EndpointId endpoint);
void ESPMatterProxyValidClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPulseWidthModulationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPulseWidthModulationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPumpConfigurationAndControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPumpConfigurationAndControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterPushAvStreamTransportClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPushAvStreamTransportClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterRadonConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRadonConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterRefrigeratorAlarmClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRefrigeratorAlarmClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterRefrigeratorAndTemperatureControlledCabinetModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRefrigeratorAndTemperatureControlledCabinetModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterRelativeHumidityMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRelativeHumidityMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterRvcCleanModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRvcCleanModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterRvcOperationalStateClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRvcOperationalStateClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterRvcRunModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRvcRunModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterSampleMeiClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSampleMeiClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterScenesManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterScenesManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterServiceAreaClusterServerInitCallback(EndpointId endpoint);
void ESPMatterServiceAreaClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterSmokeCoAlarmClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSmokeCoAlarmClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterSoftwareDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSoftwareDiagnosticsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterSoilMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSoilMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterSwitchClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSwitchClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterTargetNavigatorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTargetNavigatorClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterTemperatureControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTemperatureControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterTemperatureMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTemperatureMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterThermostatClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThermostatClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterThermostatUserInterfaceConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThermostatUserInterfaceConfigurationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterThreadBorderRouterManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThreadBorderRouterManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterThreadNetworkDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThreadNetworkDiagnosticsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterThreadNetworkDirectoryClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThreadNetworkDirectoryClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterTimeFormatLocalizationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTimeFormatLocalizationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterTimeSynchronizationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTimeSynchronizationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterTlsCertificateManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTlsCertificateManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterTlsClientManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTlsClientManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterTotalVolatileOrganicCompoundsConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTotalVolatileOrganicCompoundsConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterUnitLocalizationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterUnitLocalizationClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterUnitTestingClusterServerInitCallback(EndpointId endpoint);
void ESPMatterUnitTestingClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterUserLabelClusterServerInitCallback(EndpointId endpoint);
void ESPMatterUserLabelClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterValveConfigurationAndControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterValveConfigurationAndControlClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterWakeOnLanClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWakeOnLanClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterWaterHeaterManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWaterHeaterManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterWaterHeaterModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWaterHeaterModeClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterWebRTCTransportProviderClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWebRTCTransportProviderClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterWebRTCTransportRequestorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWebRTCTransportRequestorClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterWiFiNetworkDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWiFiNetworkDiagnosticsClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterWiFiNetworkManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWiFiNetworkManagementClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterWindowCoveringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWindowCoveringClusterServerShutdownCallback(EndpointId endpoint);

void ESPMatterZoneManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterZoneManagementClusterServerShutdownCallback(EndpointId endpoint);

