#pragma once

#include <lib/core/DataModelTypes.h>
#include <app/server-cluster/ServerClusterInterface.h>

using chip::EndpointId;
using chip::app::ClusterShutdownType;

void ESPMatterAccessControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAccessControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterAccountLoginClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAccountLoginClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterActionsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterActionsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterActivatedCarbonFilterMonitoringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterActivatedCarbonFilterMonitoringClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterAdministratorCommissioningClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAdministratorCommissioningClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterAirQualityClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAirQualityClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterAmbientContextSensingClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAmbientContextSensingClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterApplicationBasicClusterServerInitCallback(EndpointId endpoint);
void ESPMatterApplicationBasicClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterApplicationLauncherClusterServerInitCallback(EndpointId endpoint);
void ESPMatterApplicationLauncherClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterAudioOutputClusterServerInitCallback(EndpointId endpoint);
void ESPMatterAudioOutputClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterBallastConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBallastConfigurationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterBasicInformationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBasicInformationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterBindingClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBindingClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterBooleanStateClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBooleanStateClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterBooleanStateConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBooleanStateConfigurationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterBridgedDeviceBasicInformationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterBridgedDeviceBasicInformationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterCameraAvSettingsUserLevelManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCameraAvSettingsUserLevelManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterCameraAvStreamManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCameraAvStreamManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterCarbonDioxideConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCarbonDioxideConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterCarbonMonoxideConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCarbonMonoxideConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterChannelClusterServerInitCallback(EndpointId endpoint);
void ESPMatterChannelClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterChimeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterChimeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterClosureControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterClosureControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterClosureDimensionClusterServerInitCallback(EndpointId endpoint);
void ESPMatterClosureDimensionClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterColorControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterColorControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterCommissionerControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCommissionerControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterCommodityMeteringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCommodityMeteringClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterCommodityPriceClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCommodityPriceClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterCommodityTariffClusterServerInitCallback(EndpointId endpoint);
void ESPMatterCommodityTariffClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterContentAppObserverClusterServerInitCallback(EndpointId endpoint);
void ESPMatterContentAppObserverClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterContentControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterContentControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterContentLauncherClusterServerInitCallback(EndpointId endpoint);
void ESPMatterContentLauncherClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterDescriptorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDescriptorClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterDeviceEnergyManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDeviceEnergyManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterDeviceEnergyManagementModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDeviceEnergyManagementModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterDiagnosticLogsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDiagnosticLogsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterDishwasherAlarmClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDishwasherAlarmClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterDishwasherModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDishwasherModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterDoorLockClusterServerInitCallback(EndpointId endpoint);
void ESPMatterDoorLockClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterEcosystemInformationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEcosystemInformationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterElectricalEnergyMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterElectricalEnergyMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterElectricalGridConditionsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterElectricalGridConditionsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterElectricalPowerMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterElectricalPowerMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterEnergyEvseClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEnergyEvseClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterEnergyEvseModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEnergyEvseModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterEnergyPreferenceClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEnergyPreferenceClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterEthernetNetworkDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterEthernetNetworkDiagnosticsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterFanControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFanControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterFaultInjectionClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFaultInjectionClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterFixedLabelClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFixedLabelClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterFlowMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFlowMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterFormaldehydeConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterFormaldehydeConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterGeneralCommissioningClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGeneralCommissioningClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterGeneralDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGeneralDiagnosticsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterGroupKeyManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGroupKeyManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterGroupcastClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGroupcastClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterGroupsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterGroupsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterHepaFilterMonitoringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterHepaFilterMonitoringClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterIcdManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterIcdManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterIdentifyClusterServerInitCallback(EndpointId endpoint);
void ESPMatterIdentifyClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterIlluminanceMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterIlluminanceMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterJointFabricAdministratorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterJointFabricAdministratorClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterJointFabricDatastoreClusterServerInitCallback(EndpointId endpoint);
void ESPMatterJointFabricDatastoreClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterKeypadInputClusterServerInitCallback(EndpointId endpoint);
void ESPMatterKeypadInputClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterLaundryDryerControlsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLaundryDryerControlsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterLaundryWasherControlsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLaundryWasherControlsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterLaundryWasherModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLaundryWasherModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterLevelControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLevelControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterLocalizationConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLocalizationConfigurationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterLowPowerClusterServerInitCallback(EndpointId endpoint);
void ESPMatterLowPowerClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterMediaInputClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMediaInputClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterMediaPlaybackClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMediaPlaybackClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterMessagesClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMessagesClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterMeterIdentificationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMeterIdentificationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterMicrowaveOvenControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMicrowaveOvenControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterMicrowaveOvenModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterMicrowaveOvenModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterModeSelectClusterServerInitCallback(EndpointId endpoint);
void ESPMatterModeSelectClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterNetworkCommissioningClusterServerInitCallback(EndpointId endpoint);
void ESPMatterNetworkCommissioningClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterNitrogenDioxideConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterNitrogenDioxideConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOccupancySensingClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOccupancySensingClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOnOffClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOnOffClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOperationalCredentialsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOperationalCredentialsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOperationalStateClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOperationalStateClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOtaSoftwareUpdateProviderClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOtaSoftwareUpdateProviderClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOtaSoftwareUpdateRequestorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOtaSoftwareUpdateRequestorClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOvenCavityOperationalStateClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOvenCavityOperationalStateClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOvenModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOvenModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterOzoneConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterOzoneConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPm10ConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPm10ConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPm1ConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPm1ConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPm25ConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPm25ConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPowerSourceClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPowerSourceClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPowerSourceConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPowerSourceConfigurationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPowerTopologyClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPowerTopologyClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPressureMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPressureMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterProxyConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterProxyConfigurationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterProxyDiscoveryClusterServerInitCallback(EndpointId endpoint);
void ESPMatterProxyDiscoveryClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterProxyValidClusterServerInitCallback(EndpointId endpoint);
void ESPMatterProxyValidClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPulseWidthModulationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPulseWidthModulationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPumpConfigurationAndControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPumpConfigurationAndControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterPushAvStreamTransportClusterServerInitCallback(EndpointId endpoint);
void ESPMatterPushAvStreamTransportClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterRadonConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRadonConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterRefrigeratorAlarmClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRefrigeratorAlarmClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterRefrigeratorAndTemperatureControlledCabinetModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRefrigeratorAndTemperatureControlledCabinetModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterRelativeHumidityMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRelativeHumidityMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterRvcCleanModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRvcCleanModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterRvcOperationalStateClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRvcOperationalStateClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterRvcRunModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterRvcRunModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterSampleMeiClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSampleMeiClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterScenesManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterScenesManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterServiceAreaClusterServerInitCallback(EndpointId endpoint);
void ESPMatterServiceAreaClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterSmokeCoAlarmClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSmokeCoAlarmClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterSoftwareDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSoftwareDiagnosticsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterSoilMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSoilMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterSwitchClusterServerInitCallback(EndpointId endpoint);
void ESPMatterSwitchClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterTargetNavigatorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTargetNavigatorClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterTemperatureControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTemperatureControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterTemperatureMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTemperatureMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterThermostatClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThermostatClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterThermostatUserInterfaceConfigurationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThermostatUserInterfaceConfigurationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterThreadBorderRouterManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThreadBorderRouterManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterThreadNetworkDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThreadNetworkDiagnosticsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterThreadNetworkDirectoryClusterServerInitCallback(EndpointId endpoint);
void ESPMatterThreadNetworkDirectoryClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterTimeFormatLocalizationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTimeFormatLocalizationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterTimeSynchronizationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTimeSynchronizationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterTlsCertificateManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTlsCertificateManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterTlsClientManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTlsClientManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterTotalVolatileOrganicCompoundsConcentrationMeasurementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterTotalVolatileOrganicCompoundsConcentrationMeasurementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterUnitLocalizationClusterServerInitCallback(EndpointId endpoint);
void ESPMatterUnitLocalizationClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterUnitTestingClusterServerInitCallback(EndpointId endpoint);
void ESPMatterUnitTestingClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterUserLabelClusterServerInitCallback(EndpointId endpoint);
void ESPMatterUserLabelClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterValveConfigurationAndControlClusterServerInitCallback(EndpointId endpoint);
void ESPMatterValveConfigurationAndControlClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWakeOnLanClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWakeOnLanClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWaterHeaterManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWaterHeaterManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWaterHeaterModeClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWaterHeaterModeClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWaterTankLevelMonitoringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWaterTankLevelMonitoringClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWebRTCTransportProviderClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWebRTCTransportProviderClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWebRTCTransportRequestorClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWebRTCTransportRequestorClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWiFiNetworkDiagnosticsClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWiFiNetworkDiagnosticsClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWiFiNetworkManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWiFiNetworkManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterWindowCoveringClusterServerInitCallback(EndpointId endpoint);
void ESPMatterWindowCoveringClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

void ESPMatterZoneManagementClusterServerInitCallback(EndpointId endpoint);
void ESPMatterZoneManagementClusterServerShutdownCallback(EndpointId endpoint, ClusterShutdownType shutdownType);

