# Generating app/AppBuildConfig.h
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/app/AppBuildConfig.h
"#pragma once\n
#include <sdkconfig.h>\n

#ifdef CONFIG_CHIP_CONFIG_IM_PRETTY_PRINT
#define CHIP_CONFIG_IM_PRETTY_PRINT 1
#else
#define CHIP_CONFIG_IM_PRETTY_PRINT 0
#endif

#define CHIP_CONFIG_IM_FORCE_FABRIC_QUOTA_CHECK 0
#define CHIP_CONFIG_ENABLE_SESSION_RESUMPTION 1
#define CHIP_CONFIG_ACCESS_CONTROL_POLICY_LOGGING_VERBOSITY 0

#ifdef CONFIG_ENABLE_PERSIST_SUBSCRIPTIONS
#define CHIP_CONFIG_PERSIST_SUBSCRIPTIONS 1
#define CHIP_CONFIG_SUBSCRIPTION_TIMEOUT_RESUMPTION 1
#else
#define CHIP_CONFIG_PERSIST_SUBSCRIPTIONS 0
#define CHIP_CONFIG_SUBSCRIPTION_TIMEOUT_RESUMPTION 0
#endif

#ifdef CONFIG_DISABLE_READ_CLIENT
#define CHIP_CONFIG_ENABLE_READ_CLIENT 0
#else
#define CHIP_CONFIG_ENABLE_READ_CLIENT 1
#endif

#define CHIP_CONFIG_STATIC_GLOBAL_INTERACTION_MODEL_ENGINE 1
#define TIME_SYNC_ENABLE_TSC_FEATURE 1
#define NON_SPEC_COMPLIANT_OTA_ACTION_DELAY_FLOOR -1
#define CHIP_DEVICE_CONFIG_DYNAMIC_SERVER 0
#define CHIP_CONFIG_ENABLE_BUSY_HANDLING_FOR_OPERATIONAL_SESSION_SETUP 1
#define CHIP_CONFIG_DATA_MODEL_EXTRA_LOGGING 0
#define CHIP_CONFIG_TERMS_AND_CONDITIONS_REQUIRED 0
")
