# Generating core/CHIPBuildConfig.h
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/core/CHIPBuildConfig.h
"#pragma once\n
#include <sdkconfig.h>\n
#define CHIP_FUZZING_ENABLED 0

#ifdef CONFIG_BUILD_CHIP_TESTS
#define CHIP_CONFIG_TEST 1
#else
#define CHIP_CONFIG_TEST 0
#endif

#define CHIP_ERROR_LOGGING (CONFIG_CHIP_LOG_DEFAULT_LEVEL >= 1)
#define CHIP_PROGRESS_LOGGING (CONFIG_CHIP_LOG_DEFAULT_LEVEL >= 3)
#define CHIP_DETAIL_LOGGING (CONFIG_CHIP_LOG_DEFAULT_LEVEL >= 4)
#define CHIP_CONFIG_LOG_MESSAGE_MAX_SIZE 256
#define CHIP_AUTOMATION_LOGGING (CONFIG_CHIP_LOG_DEFAULT_LEVEL >= 5)
#define CHIP_PW_TOKENIZER_LOGGING 0
#define CHIP_EXCHANGE_NODE_ID_LOGGING 0
#define CHIP_CONFIG_SHORT_ERROR_STR 1
#define CHIP_CONFIG_ENABLE_ARG_PARSER 1
#define CHIP_TARGET_STYLE_UNIX 0
#define CHIP_TARGET_STYLE_EMBEDDED 1
#define CHIP_CONFIG_MEMORY_MGMT_MALLOC 0
#define HAVE_MALLOC 0
#define HAVE_FREE 0
#define HAVE_NEW 0
#define CHIP_CONFIG_MEMORY_MGMT_PLATFORM 1
#define CHIP_CONFIG_MEMORY_DEBUG_CHECKS 0
#define CHIP_CONFIG_MEMORY_DEBUG_DMALLOC 0
#define CHIP_CONFIG_PROVIDE_OBSOLESCENT_INTERFACES 0
#define CHIP_CONFIG_TRANSPORT_TRACE_ENABLED 0
#define CHIP_CONFIG_TRANSPORT_PW_TRACE_ENABLED 0
#define CHIP_CONFIG_MINMDNS_DYNAMIC_OPERATIONAL_RESPONDER_LIST 0
#define CHIP_CONFIG_MINMDNS_MAX_PARALLEL_RESOLVES 2
#define CHIP_CONFIG_CANCELABLE_HAS_INFO_STRING_FIELD 0
#define CHIP_CONFIG_BIG_ENDIAN_TARGET 0
#define CHIP_CONFIG_TLV_VALIDATE_CHAR_STRING_ON_WRITE 1
#define CHIP_CONFIG_TLV_VALIDATE_CHAR_STRING_ON_READ 0
#define CHIP_CONFIG_COMMAND_SENDER_BUILTIN_SUPPORT_FOR_BATCHED_COMMANDS 0
#define CHIP_CONFIG_TEST_GOOGLETEST 0
#define CHIP_CONFIG_MRP_ANALYTICS_ENABLED 0
")
