# Generating app/icd/server/ICDServerBuildConfig.h
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/app/icd/server/ICDServerBuildConfig.h
"#pragma once\n
#include <sdkconfig.h>\n
#ifdef CONFIG_ENABLE_ICD_SERVER
#define CHIP_CONFIG_ENABLE_ICD_SERVER 1
#else
#define CHIP_CONFIG_ENABLE_ICD_SERVER 0
#endif

#ifdef CONFIG_ENABLE_ICD_LIT
#define CHIP_CONFIG_ENABLE_ICD_LIT 1
#else
#define CHIP_CONFIG_ENABLE_ICD_LIT 0
#endif

#ifdef CONFIG_ENABLE_ICD_CIP
#define CHIP_CONFIG_ENABLE_ICD_CIP 1
#else
#define CHIP_CONFIG_ENABLE_ICD_CIP 0
#endif

#ifdef CONFIG_ENABLE_ICD_USER_ACTIVE_MODE_TRIGGER
#define CHIP_CONFIG_ENABLE_ICD_UAT 1
#else
#define CHIP_CONFIG_ENABLE_ICD_UAT 0
#endif

#define CHIP_CONFIG_ENABLE_ICD_DSLS 0

#ifdef CONFIG_ICD_REPORT_ON_ACTIVE_MODE
#define ICD_REPORT_ON_ENTER_ACTIVE_MODE 1
#else
#define ICD_REPORT_ON_ENTER_ACTIVE_MODE 0
#endif

#ifdef CONFIG_ICD_MAX_NOTIFICATION_SUBSCRIBERS
#define ICD_MAX_NOTIFICATION_SUBSCRIBERS CONFIG_ICD_MAX_NOTIFICATION_SUBSCRIBERS
#else
#define ICD_MAX_NOTIFICATION_SUBSCRIBERS 1
#endif
")
