# Automatically added defines for script
#define BLE_PROJECT_CONFIG_INCLUDE 1
#define INET_PROJECT_CONFIG_INCLUDE 1
#define LWIP_DEBUG 1
#define CHIP_DEVICE_CONFIG_ENABLE_NFC 1
#define CONFIG_CHIP_NFC_COMMISSIONING 1
#define CHIP_DEVICE_PROJECT_CONFIG_INCLUDE 1
#define CHIP_DEVICE_CONFIG_FIRWMARE_BUILD_DATE 1 // codespell:ignore
#define CHIP_DEVICE_CONFIG_ENABLE_WIFI 1
#define CHIP_DEVICE_LAYER_TARGET_NXP_ZEPHYR 1
#define CHIP_DEVICE_ENABLE_DATA_MODEL 1
#define CHIP_DEVICE_LAYER_TARGET_${possible_device_layer_target_define} 1
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION 1
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING 1
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 1
#define CHIP_DEVICE_LAYER_NONE 1
#define EXTERNAL_KEYVALUESTOREMANAGERIMPL_HEADER 1
#define SYSTEM_ENABLE_CLANG_THREAD_SAFETY_ANALYSIS 1 (configuration by gn 'is_clang')
#define CHIP_CONFIG_SKIP_APP_SPECIFIC_GENERATED_HEADER_INCLUDES 0
#define CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT 0
