#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module

import datetime

try:
    from conf_common import *
except ImportError:
    import os
    import sys

    sys.path.insert(0, os.path.abspath("../"))
    from conf_common import *

# General information about the project.
project = "Espressif's SDK for Matter"
copyright = f"2022 - {datetime.datetime.now(tz=datetime.timezone.utc).year}, Espressif Systems (Shanghai) Co., Ltd"
pdf_title = "ESP-Matter Programming Guide"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"
