# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/blemesh_bridge:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3"]
      temporary: true
      reason: the other targets are not tested yet

examples/zap_light:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/light_switch:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c6", "esp32c2", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/light:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/generic_switch:
  enable:
    - if: IDF_TARGET in ["esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/esp-now_bridge_light:
  enable:
    - if: IDF_TARGET in ["esp32c3"]
      temporary: true
      reason: the other targets are not tested yet

examples/controller:
  enable:
    - if: IDF_TARGET in ["esp32"]
      temporary: true
      reason: the other targets are not tested yet

examples/zigbee_bridge:
  enable:
    - if: IDF_TARGET in ["esp32"]
      temporary: true
      reason: the other targets are not tested yet

examples/room_air_conditioner:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/refrigerator:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/all_device_types_app:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/mfg_test_app:
  enable:
    - if: IDF_TARGET in ["esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/sleepy_device:
  enable:
    - if: IDF_TARGET in ["esp32h2"]
      temporary: true
      reason: the other targets are not tested yet
