# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

# Disabling the external platform builds till we fix the build problem
# due to https://github.com/project-chip/connectedhomeip/pull/30531
# JIRA tracker: CON-942
examples/bridge_apps/blemesh_bridge:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3"]
      temporary: true
      reason: the other targets are not tested yet

examples/zap_light:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/light_switch:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c6", "esp32c2", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/light:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/generic_switch:
  enable:
    - if: IDF_TARGET in ["esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/multiple_on_off_plugin_units:
  enable:
    - if: IDF_TARGET in ["esp32c3", "esp32", "esp32s3", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/bridge_apps/esp-now_bridge_light:
  enable:
    - if: IDF_TARGET in ["esp32c3"]
      temporary: true
      reason: the other targets are not tested yet

examples/controller:
  enable:
    - if: IDF_TARGET in ["esp32"]
      temporary: true
      reason: the other targets are not tested yet

examples/bridge_apps/zigbee_bridge:
  enable:
    - if: IDF_TARGET in ["esp32s3"]
      temporary: true
      reason: the other targets are not tested yet

examples/room_air_conditioner:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/refrigerator:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/all_device_types_app:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32h2", "esp32c2"]
      temporary: true
      reason: the other targets are not tested yet

examples/mfg_test_app:
  enable:
    - if: IDF_TARGET in ["esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/icd_app:
  enable:
    - if: IDF_TARGET in ["esp32h2", "esp32c6"]
      temporary: true
      reason: the other targets are not tested yet

examples/demo/badge:
   enable:
    - if: IDF_TARGET in ["esp32"]
      temporary: true
      reason: the other targets are not tested yet

examples/managed_component_light:
   enable:
    - if: IDF_TARGET in [""]
      temporary: true
      reason: this should be compiled without setting up environment, another CI has been added

examples/door_lock:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32c2", "esp32c6", "esp32h2"]
      temporary: true
      reason: the other targets are not tested yet

examples/ota_provider:
  enable:
    - if: IDF_TARGET in ["esp32s3"]
      temporary: true
      reason: the other targets are not tested yet

examples/light_wifi_prov:
  enable:
    - if: IDF_TARGET in ["esp32s3", "esp32c3"]
      temporary: true
      reason: the other targets are not tested yet

examples/thread_border_router:
  enable:
    - if: IDF_TARGET in ["esp32s3"]
      temporary: true
      reason: the other targets are not tested yet

examples/bridge_apps/bridge_cli:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c3"]
      temporary: true
      reason: the other targets are not tested yet

examples/sensors:
  enable:
    - if: IDF_TARGET in ["esp32c3"]
      temporary: true
      reason: the other targets are not tested yet
